### ISSUE TITLE
Unsure why number coming out in base 16

### ISSUE THREAD

**Issue by Rambatino** [k0kubun/pp#27]
My structs, when printed look like: 

``` golang
db.Company{
  ID:                          0x4c58da13a2c8001,
  Credits:                     0x01f2,
  RetryAttempts:               0x0000,
  LeadCallerID:                0x0000,
  CallRecording:               false,
```

How do I convert?

**Comment by itchyny** [comment]
The number of unsigned int is printed in hex and this is an expected behavior within this library. I think the author implemented the printer of uintX in hex based on the behavior of `fmt.Sprintf("%#v", x)` and it's reasonable. I understand there're some situations where we want to show unsigned int in deciaml though.

**Comment by Rambatino** [comment]
I shall close. Thanks @itchyny.
