### ISSUE TITLE
Option for thousands separator

### ISSUE THREAD

**Issue by mariusgrigoriu** [k0kubun/pp#53]
It seems like it would be a good idea to have an option for a thousands separator for floats and ints, which can make structs with many large numbers easier to read. For example: 

```
myStruct{
  myfloat: 1,000,000.00,
}
```

What do you think?

**Comment by k0kubun** [comment]
How about `1_000_000.00` instead? It seems like the literal was added in Go 1.13, so the format could be useful to keep it valid as a Go literal.

Also, do you have any idea about the option name? WDYT about:

```go
mypp = pp.New()
mypp.SetNumberDelimiter(true)
mypp.Println(...)
```

**Comment by k0kubun** [comment]
Let's reopen this when we get attention on this again.

**Comment by mariusgrigoriu** [comment]
The term encountered most often with other applications seems to be thousands separator. Would that make it: 
```go
mypp = pp.New()
mypp.SetThousandsSeparator(true)
mypp.Println(...)
```

Is the idea that the output from pp can be pasted as Go code? If so the underscores probably makes sense. If legibility is the primary concern, what if we take a character instead of a bool like so:
```go
mypp = pp.New()
mypp.SetThousandsSeparator(",")
mypp.Println(...)
```
That way people can use whatever value suits them. Or perhaps let `golang.org/x/text/messages` handle the localization?

**Comment by k0kubun** [comment]
`SetThousandsSeparator` looks good to me. I'm also okay with `","` instead of `true`, but if you don't intend to allow everything there, another option could be to use `','`.

It seems like we have a plan now. Would you be interested in adding it? We recently added some other options https://github.com/k0kubun/pp/pull/55 https://github.com/k0kubun/pp/pull/60, which might help you prepare it.
