### ISSUE TITLE
Verb '%T' is working incorrectly in formatted print

### ISSUE THREAD

**Issue by bragov4ik** [k0kubun/pp#58]
#### Problem:
Passing any variable to `pp.Printf` under formatting `%T` always results in `string` type, even when the actual type is different (for example, `int`).
#### Code to reproduce:
```
package main

import (
	"fmt"

	"github.com/k0kubun/pp"
)

func main() {
	a := 1
	fmt.Printf("%T\n", a)
	pp.Printf("%T\n", a)
}
```
#### Actual output:
```
int
string
```
#### Expected output:
```
int
int
```
#### Versions:
Go version - 1.17.1
Package (pp) version - 3.0.7 (`github.com/k0kubun/pp/v3`)

**Comment by k0kubun** [comment]
Intentional. Please see how it's implemented https://github.com/k0kubun/pp/blob/b87d88f85b84fd33fb9c0e20a2617d7cb2464dd4/pp.go#L56-L58. You're supposed to use only `%s` in the format of `pp.Printf`. You have to separately call `fmt.Printf` if you want to use `%T`. There's no reasonable way that `%T` and pretty-printed `%s` work in a single call.

**Comment by k0kubun** [comment]
If you need to mix `%T` and pretty-printed `%s`, please try something like: `fmt.Printf("%T %s", a, pp.Sprint(b))`.

**Comment by bragov4ik** [comment]
Ok, description and name of the method made an impression that it should behave the same way as `fmt` functions. Thanks for explanation.
