### ISSUE TITLE
Printf not work correctly

### ISSUE THREAD

**Issue by aj3423** [k0kubun/pp#70]
```go
func main() {
	pp.Printf("%d", 123)
	fmt.Println()
}
```
The code outputs
> %!d(string=123)

I'm using the latest version: v3.1.1-0.20220216035903-af1e26e8087e

**Comment by k0kubun** [comment]
It might feel weird (please feel free to submit a pull request to correct the document) but this is actually intentional. The format is supposed to take only `%s`. Because pp always interprets a type and the conversion outcome is always `%s`, there's actually no motivation to support specifiers other than `%s`.
